services:
  app:
    build: .
    container_name: infra_helpdesk_app
    ports:
      - "3002:3002"   # host:container
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_DB: it_tickets
      MYSQL_PORT: "3306"
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: ""
      DB_PORT: "3306"
      DB_NAME: lead_management
    volumes:
      - .:/app

  db:
    image: mysql:8
    container_name: infra_helpdesk_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: it_tickets
    volumes:
      - mysql_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  mysql_volume:
